### ISSUE TITLE
Open discussions on direct messages

### ISSUE THREAD

**Issue by marceloschmidt** [debdutdeb/rocket.chat.apps.discuss#1]
You could open a `/discuss Discussion Name` on a Direct Message too.

**Comment by debdutdeb** [comment]
Hmm, looks like we can only create a discussion in a dm if we use the more options menu on an existing message. The create discussion modal doesn't index dm rooms.

**Comment by marceloschmidt** [comment]
I am on a DM with Rocket.Cat and mine shows the create discussions option.

![image](https://user-images.githubusercontent.com/1986378/147926382-80d6487b-fa6e-46ae-834c-44c7f1427b0d.png)

**Comment by debdutdeb** [comment]
I see, I've nver used that button for discussion creation, so missed that one. 

If you use the top left 'create' button to create a discussion, you'll see no dms are indexed. Presuming a bug.

**Comment by marceloschmidt** [comment]
Gotcha, makes sense.

**Comment by debdutdeb** [comment]
Closed by https://github.com/debdutdeb/rocket.chat.apps.discuss/commit/7585d2cb55ff867d62ef826681a3da77868fb398
