### ISSUE TITLE
Duplicate discussions within a thread

### ISSUE THREAD

**Issue by marceloschmidt** [debdutdeb/rocket.chat.apps.discuss#2]
If you are on a thread and type `/discuss` you'll open a discussion with the thread name, which is cool.
But if someone already typed `/discuss` on the thread and you do it too, maybe it would be more interesting to join the current discussion instead of creating a second discussion with the same name.

**Comment by debdutdeb** [comment]
Closed in https://github.com/debdutdeb/rocket.chat.apps.discuss/commit/37dde0230a1634cd5fddc4935af6229dcd72331f
