### ISSUE TITLE
I can create discussions on rooms that I am not a part of

### ISSUE THREAD

**Issue by marceloschmidt** [debdutdeb/rocket.chat.apps.discuss#3]
If a room is public, but I am not a part of it, I can still create discussions on it.

![image](https://user-images.githubusercontent.com/1986378/147926186-a423d688-3c70-4177-92ce-1efb28278bd5.png)

**Comment by debdutdeb** [comment]
Closed by https://github.com/debdutdeb/rocket.chat.apps.discuss/commit/7585d2cb55ff867d62ef826681a3da77868fb398
